### ISSUE TITLE
How to add pubKey dynamically? 

### ISSUE THREAD

**Issue by okadts** [uploadcare/blocks-examples#8]
### Question

How to add pubKey dynamically? I'm on Vue3

first I use:
`--cfg-pubkey: v-bind(propVar)`
Not working

Than I user :style
`:style="'--cfg-pubkey': props.publicKey"`
Not working

Any suggestion?

**Comment by nd0ut** [comment]
Hey @okadts,

you need to call `element.updateCssData()` after an update. It could be done using [Template Refs](https://vuejs.org/guide/essentials/template-refs.html)

**Comment by okadts** [comment]
Thanks @nd0ut 
I tried that one, but is not working
So I use below

`props: {
    publicKey: {
      type: String,
      default: ''
    }}`

Than I add on the setup(.... :

`const pubKey = ref(`"${props.publicKey}"`)`

add pubKey to the return also

Lastly on the style :

`--cfg-pubkey: v-bind(pubKey);`

Now it works 👍 
Probably Vue miss out to make the css vas is a string, but not so sure about it
At least is working now
